language: ruby
rvm:
- 2.5
deploy:
  provider: rubygems
  api_key:
    secure: fAmrDgaEj29FTiwB/Iy4pX+QiLHTo4MbUw1JeUqMAK/RgDlx0OnTK7J25hfZYScb2tr7xliooC4abQAIzzdrT8J1Pb4qp53G4pwiVcbvf+bXWHJDZDGxNAeGDsvB4EEHhPWJCajIOkx7qEf1+R7Je82MjppeqC0EXx+AO3tDTfQ=
  gem: lisbn
  on:
    tags: true
    repo: ragalie/lisbn
